### ISSUE TITLE
Nice codeplug, but a question

### ISSUE THREAD

**Issue by N1KPW** [drewmccal/anytone-878-northeast-codeplug#2]
in the Connecticut section of the Codeplug, exactly what town is the "NRT" abbreviation being used for?? I can't, for the life of me, match a town to the letters in my head..just wondering if its an area I normally find myself in or not... This helped me alot to get started with building my own codeplug for 878, working nicely with hotspot, still some work to do with repeaters...

**Comment by drewmccal** [comment]
"NRT" must have been one of the stations that I inherited from the NEDECN code plug.  I'm guessing it is Northford, CT?  I'm glad the codeplug was a help.  There was significantly less info online last fall for the 878.
